name: Build and Deploy
on:
  push: 
    branch:
      - develop
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
      
      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1
        with:
          API_KEY : ${{ secrets.API_KEY }}
          AUTH_DOMAIN : ${{ secrets.AUTH_DOMAIN }}
          PROJECT_ID : ${{ secrets.PROJECT_ID }}
          STORAGE_BUCKET : ${{ secrets.STORAGE_BUCKET }}
          MESSAGING_SENDER_ID : ${{ secrets.MESSAGING_SENDER_ID }}
          APP_ID : ${{ secrets.APP_ID }}
          MEASUREMENT_ID : ${{ secrets.MEASUREMENT_ID }}
          TEST : ${{ secrets.TEST }}
          directory: '/project-react-3-yoonhe'
          file_name: .env
          
 

      - name: Install and Build 🔧 
        run: |
          npm install
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: dist